[package]
name = "og-core"
version = "0.70.1"
edition = "2021"
description = "Event-first, schema-less document database kernel"
license = "MIT"
publish = false

[lib]
name = "og_core"
path = "src/lib.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
rmp-serde = "1"
serde_json = "1"
rustyline = "15"
ed25519-dalek = "2"
argon2 = "0.5"
chacha20poly1305 = "0.10"
rpassword = "7"
notify = "8"
tungstenite = { version = "0.30.0", features = ["rustls-tls-webpki-roots"] }

[target.'cfg(all(target_pointer_width = "64", target_family = "unix"))'.dependencies]
mmap-guard = "=0.2.2"

[dev-dependencies]
proptest = "1"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
