//! End-to-end tests of the textual query language on the production runtime.
#![cfg_attr(rustfmt, rustfmt_skip)]

use std::sync::Arc;

use og_core::{
    engine::Engine,
    query::{parse, value_expression_runtime, PlannerPipeline, QueryRuntimeMaterializationExt, ScanPlanLowerer},
    storage::{CollectionId, DocumentId, MemoryStorage, StorageEngine},
    Document, Value,
};

fn seed(storage: &MemoryStorage, collection: &str, rows: &[&[(&str, Value)]]) {
    let collection = CollectionId::parse(collection).unwrap();
    let mut transaction = storage.begin().unwrap();
    for (index, fields) in rows.iter().enumerate() {
        let id = DocumentId::parse(format!("01900000-0000-7000-8000-{:012x}", index + 1)).unwrap();
        let document = Document::from_fields(fields.iter().map(|(name, value)| (*name, value.clone())));
        transaction.insert(&collection, id, Arc::new(document)).unwrap();
    }
    transaction.commit().unwrap();
}

fn engine() -> Engine {
    let storage = Arc::new(MemoryStorage::new());
    seed(&storage, "users", &[
        &[("name", Value::from("Alice")), ("age", Value::from(31_i64)), ("country", Value::from("FR")), ("active", Value::from(true)), ("balance", Value::from(10_i64))],
        &[("name", Value::from("Bob")), ("age", Value::from(17_i64)), ("country", Value::from("FR")), ("active", Value::from(false)), ("balance", Value::from(-3_i64))],
        &[("name", Value::from("Carol")), ("age", Value::from(45_i64)), ("country", Value::from("DE")), ("active", Value::from(true)), ("balance", Value::from(-12_i64))],
    ]);
    seed(&storage, "orders", &[
        &[("region", Value::from("EU")), ("qty", Value::from(2_i64)), ("price", Value::from(10_i64)), ("status", Value::from("paid"))],
        &[("region", Value::from("EU")), ("qty", Value::from(1_i64)), ("price", Value::from(99_i64)), ("status", Value::from("paid"))],
        &[("region", Value::from("US")), ("qty", Value::from(4_i64)), ("price", Value::from(250_i64)), ("status", Value::from("pending"))],
    ]);
    let runtime = Arc::new(value_expression_runtime().unwrap().with_default_materialization("test"));
    Engine::new(storage, runtime, Arc::new(ScanPlanLowerer::new()))
}

fn pipeline(text: &str) -> PlannerPipeline {
    let ast = parse(text).unwrap_or_else(|error| panic!("{text}: {error}"));
    PlannerPipeline::from_ast(text, &ast).unwrap_or_else(|error| panic!("{text}: {error}"))
}

/// Runs a read query the way `ogd` does: streaming or governed-blocking, never materialized.
fn stream(engine: &Engine, text: &str) -> Vec<Document> {
    let planned = engine.plan(&pipeline(text)).unwrap_or_else(|error| panic!("{text}: {error}"));
    let mut rows = Vec::new();
    let executed = if engine.supports_governed_blocking_streaming(planned.physical()) {
        engine.stream_governed_blocking_pipeline(planned.physical(), &mut |row| { rows.push(row.document().clone()); Ok(()) })
    } else {
        engine.stream_read_pipeline(planned.physical(), &mut |stored| { rows.push(stored.document().clone()); Ok(()) })
    };
    assert!(executed.unwrap_or_else(|error| panic!("{text}: {error}")).is_some(), "{text}: no bounded executor");
    rows
}

fn materialize(engine: &Engine, text: &str) -> Vec<Document> {
    let result = engine.execute(&pipeline(text)).unwrap_or_else(|error| panic!("{text}: {error}"));
    result.output().rows().iter().map(|row| row.document().clone()).collect()
}

fn names(rows: &[Document]) -> Vec<&str> {
    rows.iter().map(|row| row.get("name").and_then(Value::as_str).unwrap()).collect()
}

#[test] fn symbolic_boolean_operators_match_keywords() { let engine = engine(); for (symbolic, keyword) in [ (r#"on users | where age > 40 || country == "FR""#, r#"on users | where age > 40 or country == "FR""#), (r#"on users | where age >= 18 && active"#, r#"on users | where age >= 18 and active"#), (r#"on users | where !active"#, r#"on users | where not active"#), (r#"on users | where !(age < 18) && country == "FR""#, r#"on users | where not (age < 18) and country == "FR""#), ] { assert_eq!(names(&stream(&engine, symbolic)), names(&stream(&engine, keyword)), "{symbolic}"); } assert_eq!(names(&stream(&engine, r#"on users | where !active"#)), ["Bob"]); }
#[test] fn signed_numeric_literals_are_constants_in_every_stage() { let engine = engine(); assert_eq!(names(&stream(&engine, "on users | where balance > -5")), ["Alice", "Bob"]); assert_eq!(names(&stream(&engine, "on users | where balance <= -12 or age < +18")), ["Bob", "Carol"]); let derived = stream(&engine, r#"on users | where name == "Alice" | derive k = -2 | select k"#); assert_eq!(derived[0].get("k"), Some(&Value::from(-2_i64))); }
#[test] fn compound_group_accepts_several_measures() { let engine = engine(); let rows = stream(&engine, "on orders | group | by region | sum qty as units | sum price as revenue | end"); assert_eq!(rows.len(), 2); let eu = rows.iter().find(|row| row.get("region") == Some(&Value::from("EU"))).unwrap(); assert_eq!(eu.get("units").and_then(Value::as_number).and_then(|n| n.as_float()), Some(3.0)); assert_eq!(eu.get("revenue").and_then(Value::as_number).and_then(|n| n.as_float()), Some(109.0)); let counted = stream(&engine, "on orders | group | by status | end | sort count desc"); assert_eq!(counted[0].get("status"), Some(&Value::from("paid"))); }
#[test] fn first_is_a_declared_row_bound_on_every_execution_path() { let engine = engine(); assert_eq!(names(&stream(&engine, "on users | first")), ["Alice"]); assert_eq!(names(&stream(&engine, "on users | skip 1 | first")), ["Bob"]); assert_eq!(names(&materialize(&engine, "on users | first")), ["Alice"]); assert!(stream(&engine, "on users | where age > 100 | first").is_empty()); let projected = stream(&engine, "on users | first country"); assert_eq!(projected.len(), 1); assert!(projected[0].get("name").is_none()); assert_eq!(names(&stream(&engine, "on users | sort age desc | first")), ["Carol"]); let joined = stream(&engine, r#"on users | lookup orders | where status == "paid" | first | into first_paid | end"#); assert_eq!(joined.len(), 3); assert!(joined.iter().all(|row| row.get("first_paid").and_then(Value::as_array).map(<[Value]>::len) == Some(1))); }
#[test] fn expressions_share_one_evaluator_across_stages() { let engine = engine(); assert_eq!(names(&stream(&engine, "on users | where abs(balance) * 2 >= 20 and len(name) <= 5")), ["Alice", "Carol"]); assert_eq!(names(&stream(&engine, r#"on users | where country in ["DE", "IT"] or name not in ["Alice", "Carol"]"#)), ["Bob", "Carol"]); let derived = stream(&engine, r#"on orders | derive total = price * qty, ratio = div(total, qty - 1, 0), kind = if(total > 100, "big", "small") | select total, ratio, kind"#); assert_eq!(derived[0].get("total"), Some(&Value::from(20_i64))); assert_eq!(derived[1].get("ratio"), Some(&Value::from(0_i64))); assert_eq!(derived[2].get("kind"), Some(&Value::from("big"))); let updated = materialize(&engine, r#"on users | where name == "Bob" | set balance = balance * 2 + 1, label = upper(concat(name, "!"))"#); assert_eq!(updated[0].get("balance"), Some(&Value::from(-5_i64))); assert_eq!(updated[0].get("label"), Some(&Value::from("BOB!"))); }
#[test] fn lookup_predicates_correlate_outer_and_inner_documents() { let engine = engine(); seed_extra(&engine); let rows = stream(&engine, r#"on users as u | lookup orders as o | where exists(o.buyer) and o.buyer == u.name and o.status == "paid" | into paid | end"#); let paid = |name: &str| rows.iter().find(|row| row.get("name") == Some(&Value::from(name))).and_then(|row| row.get("paid")).and_then(Value::as_array).map(<[Value]>::len); assert_eq!(paid("Alice"), Some(2)); assert_eq!(paid("Bob"), Some(0)); let materialized = materialize(&engine, r#"on users as u | lookup orders as o | where coalesce(o.buyer, "") == u.name | into all | end"#); assert_eq!(materialized.iter().map(|row| row.get("all").and_then(Value::as_array).map_or(0, <[Value]>::len)).sum::<usize>(), 3); }
#[test] fn single_requires_exactly_one_row_on_every_path() { let engine = engine(); assert_eq!(names(&stream(&engine, r#"on users | where name == "Bob" | single"#)), ["Bob"]); for text in ["on users | single", "on users | where age > 100 | single"] { let planned = engine.plan(&pipeline(text)).unwrap(); assert!(engine.stream_read_pipeline(planned.physical(), &mut |_| Ok(())).is_err(), "{text}"); assert!(engine.execute(&pipeline(text)).is_err(), "{text}"); } }
#[test] fn sample_is_a_bounded_reservoir() { let engine = engine(); let sampled = stream(&engine, "on users | select name | sample 2"); assert_eq!(sampled.len(), 2); assert!(sampled.iter().all(|row| ["Alice", "Bob", "Carol"].contains(&row.get("name").and_then(Value::as_str).unwrap()))); assert_eq!(stream(&engine, "on users | sample 10").len(), 3); assert_eq!(stream(&engine, "on users | sample 3 | limit 1").len(), 1); assert_eq!(materialize(&engine, "on users | sample 2").len(), 2); }

fn seed_extra(engine: &Engine) { for (buyer, status) in [("Alice", "paid"), ("Alice", "paid"), ("Carol", "pending")] { engine.execute(&pipeline(&format!(r#"on orders | insert {{buyer: "{buyer}", status: "{status}", qty: 1, price: 1, region: "EU"}}"#))).unwrap(); } }
#[test] fn unwind_streams_one_row_per_array_item() { let engine = engine(); engine.execute(&pipeline(r#"on orders | insert {region: "EU", tags: ["a", "b", "c"], status: "paid"}"#)).unwrap(); engine.execute(&pipeline(r#"on orders | insert {region: "US", tags: ["d"], status: "paid"}"#)).unwrap(); let tags = |rows: &[Document]| rows.iter().map(|row| row.get("tags").and_then(Value::as_str).unwrap().to_owned()).collect::<Vec<_>>(); for text in ["on orders | where exists(tags) | unwind tags", "on orders | unwind tags | where exists(tags)"] { assert_eq!(tags(&stream(&engine, text)), ["a", "b", "c", "d"], "{text}"); assert_eq!(tags(&materialize(&engine, text)), ["a", "b", "c", "d"], "{text}"); } assert_eq!(tags(&stream(&engine, "on orders | where exists(tags) | unwind tags | skip 1 | limit 2")), ["b", "c"]); assert_eq!(tags(&stream(&engine, "on orders | where exists(tags) | unwind tags | where tags != \"b\" | select tags")), ["a", "c", "d"]); assert_eq!(stream(&engine, "on orders | where exists(tags) | unwind tags | count")[0].get("count"), Some(&Value::from(4_u64))); assert_eq!(tags(&stream(&engine, "on orders | where exists(tags) | unwind tags | sort tags desc | first")), ["d"]); }
#[test] fn unwind_after_a_bound_and_inside_lookup_streams() { let engine = engine(); engine.execute(&pipeline(r#"on orders | insert {region: "EU", tags: ["a", "b"], status: "paid"}"#)).unwrap(); let rows = stream(&engine, "on orders | where exists(tags) | limit 1 | unwind tags"); assert_eq!(rows.len(), 2); let joined = stream(&engine, r#"on users | where name == "Alice" | lookup orders | where exists(tags) | unwind tags | into tags | end"#); assert_eq!(joined[0].get("tags").and_then(Value::as_array).map(<[Value]>::len), Some(2)); }
#[test] fn blocking_stage_accepts_a_streaming_tail() { let engine = engine(); seed_extra(&engine); let same = |text: &str| { let streamed = stream(&engine, text); let materialized = materialize(&engine, text); assert_eq!(streamed, materialized, "{text}"); streamed }; assert_eq!(names(&same("on users | sort name desc | skip 1 | limit 1")), ["Bob"]); assert_eq!(names(&same("on users | sort name | skip 1")), ["Bob", "Carol"]); assert_eq!(names(&same("on users | sort name | skip 5 | limit 2")), Vec::<&str>::new()); assert_eq!(names(&same("on users | sort name | select name | skip 1 | limit 1")), ["Bob"]); let oldest = same("on users | sort age desc | first name"); assert_eq!(oldest.len(), 1); assert!(oldest[0].get("name").is_some() && oldest[0].get("age").is_none()); let grouped = same("on orders | group | by region | sum qty as units | end | select region"); assert_eq!(grouped.len(), 2); assert!(grouped.iter().all(|row| row.get("units").is_none() && row.get("region").is_some())); assert_eq!(same("on orders | group | by region | sum qty as units | end | count")[0].get("count"), Some(&Value::from(2_u64))); let sampled = stream(&engine, "on users | sample 2 | select name"); assert_eq!(sampled.len(), 2); assert!(sampled.iter().all(|row| row.get("age").is_none())); assert_eq!(same("on users | sample 10 | count")[0].get("count"), Some(&Value::from(3_u64))); assert_eq!(same("on users | sort name | where name != \"Bob\" | count")[0].get("count"), Some(&Value::from(2_u64))); assert_eq!(names(&same("on users | sort name | where name != \"Alice\" | limit 1")), ["Bob"]); }
#[test] fn lookup_and_union_accept_a_streaming_tail() { let engine = engine(); seed_extra(&engine); let joined = stream(&engine, r#"on users | lookup orders | where exists(buyer) | into orders | end | select name"#); assert_eq!(joined.len(), 3); assert!(stream(&engine, r#"on users | lookup orders | into orders | end | limit 2"#).len() == 2); assert_eq!(stream(&engine, r#"on users | union | on orders | end | count"#)[0].get("count"), Some(&Value::from(9_u64))); assert_eq!(stream(&engine, r#"on users | union | on orders | end | skip 2 | limit 3"#).len(), 3); }
#[test] fn source_alias_qualifies_fields_at_the_root() { let engine = engine(); for (aliased, plain) in [ ("on users as u | where u.age > 30", "on users | where age > 30"), ("on users as u | where u.age > 30 and u.name != \"Bob\" | sort u.name desc | select u.name", "on users | where age > 30 and name != \"Bob\" | sort name desc | select name"), ("on users as u | where u.name == \"u.age\" or len(u.name) > 3 | select u.name, u.age * 2 as double", "on users | where name == \"u.age\" or len(name) > 3 | select name, age * 2 as double"), ("on users as u | derive twice = u.age * 2 | where u.age > 30 | first", "on users | derive twice = age * 2 | where age > 30 | first") ] { assert_eq!(stream(&engine, aliased), stream(&engine, plain), "{aliased}"); assert_eq!(materialize(&engine, aliased), materialize(&engine, plain), "{aliased}"); } assert!(!stream(&engine, "on users as u | where u.age > 30").is_empty()); seed_extra(&engine); let joined = stream(&engine, r#"on users as u | lookup orders as o | where exists(o.buyer) and o.buyer == u.name | into mine | end | where u.age > 0 | select u.name"#); assert_eq!(joined.len(), 3); }
#[test] fn pivot_runs_on_a_bounded_incremental_executor() { let engine = engine(); seed_extra(&engine); for text in [ "on orders | pivot | rows region | columns status | values qty | aggregate sum | end", "on orders | where qty >= 1 | pivot | rows region | columns status | values price | aggregate max | end", "on orders | pivot | rows region | columns status | values qty | aggregate count | end" ] { let planned = engine.plan(&pipeline(text)).unwrap(); assert!(engine.supports_governed_blocking_streaming(planned.physical()), "{text}"); assert_eq!(stream(&engine, text), materialize(&engine, text), "{text}"); } let sums = stream(&engine, "on orders | pivot | rows region | columns status | values qty | aggregate sum | end"); assert_eq!(sums.len(), 2); let eu = sums.iter().find(|row| row.get("region") == Some(&Value::from("EU"))).unwrap(); assert_eq!(eu.get("paid"), Some(&Value::float(5.0).unwrap())); assert_eq!(eu.get("pending"), Some(&Value::float(1.0).unwrap())); }

#[test] fn into_inserts_the_result_into_another_collection() { let engine = engine(); let output = engine.execute(&pipeline(r#"on users | where active == true | into archive"#)).unwrap(); let statistics = output.output().statistics(); assert_eq!((statistics.scanned(), statistics.inserted(), statistics.returned()), (3, 2, 0)); assert!(output.output().rows().is_empty()); assert_eq!(names(&materialize(&engine, "on archive | sort name")), ["Alice", "Carol"]); assert_eq!(materialize(&engine, "on users").len(), 3); }
#[test] fn into_stores_projected_rows_with_fresh_ids_and_leaves_the_source_untouched() { let engine = engine(); engine.execute(&pipeline("on users | select name, _id | into names")).unwrap(); engine.execute(&pipeline("on users | select name | into names")).unwrap(); let stored = materialize(&engine, "on names | sort name"); assert_eq!(names(&stored), ["Alice", "Alice", "Bob", "Bob", "Carol", "Carol"]); assert!(stored.iter().all(|row| !row.contains_key("_id") && !row.contains_key("age"))); let ids = engine.execute(&pipeline("on names")).unwrap().into_parts().1.into_rows().iter().map(|row| row.id().to_string()).collect::<std::collections::BTreeSet<_>>(); assert_eq!(ids.len(), 6); }
#[test] fn into_accepts_aggregated_rows_and_empty_results() { let engine = engine(); engine.execute(&pipeline("on orders | group region | into totals")).unwrap(); assert_eq!(materialize(&engine, "on totals").len(), 2); let output = engine.execute(&pipeline(r#"on users | where age > 100 | into nobody"#)).unwrap(); assert_eq!(output.output().statistics().inserted(), 0); assert!(materialize(&engine, "on nobody").is_empty()); }
#[test] fn into_rejects_invalid_placements_and_targets() { let engine = engine(); for text in ["on users | into archive | limit 1", "on users | delete | into archive", "on users | into a | into b", "on users | into", "on users | into _permissions", "on users | into a b"] { assert!(engine.plan(&pipeline(text)).is_err(), "{text} must not plan"); } for text in ["on users | into users", "on users | limit 1 | into users"] { assert!(engine.execute(&pipeline(text)).is_err(), "{text} must not execute"); } assert_eq!(materialize(&engine, "on users").len(), 3); }
#[test] fn into_is_a_write_and_never_streams_as_a_read() { let engine = engine(); let planned = engine.plan(&pipeline("on users | into archive")).unwrap(); assert!(planned.physical().is_write()); assert!(!planned.logical().is_read_only()); assert!(!planned.physical().is_memory_streaming()); assert!(!engine.supports_governed_blocking_streaming(planned.physical())); }
#[test] fn into_keeps_dotted_collection_names_behind_a_source_alias() { let engine = engine(); engine.execute(&pipeline("on users as u | where u.age > 40 | into u.archive")).unwrap(); assert_eq!(names(&materialize(&engine, "on u.archive")), ["Carol"]); }
#[test] fn into_applies_the_document_scope_to_what_it_writes() { use og_core::query::DocumentScope; let engine = engine(); let scope = DocumentScope::for_place("p1"); let run = |text: &str| { let planned = engine.plan(&pipeline(text)).unwrap(); engine.execute_physical_scoped(planned.physical(), &scope).unwrap() }; assert_eq!(run("on users | into copy").statistics().inserted(), 0); run(r#"on users | insert {name: "Dana"}"#); assert_eq!(run("on users | into copy").statistics().inserted(), 1); let copied = materialize(&engine, "on copy"); assert_eq!(names(&copied), ["Dana"]); assert!(copied[0].iter().any(|(_, value)| value.as_str() == Some("p1"))); }
#[test] fn out_is_an_alias_of_into() { let engine = engine(); assert_eq!(engine.execute(&pipeline("on users | where age > 20 | out adults")).unwrap().output().statistics().inserted(), 2); assert_eq!(names(&materialize(&engine, "on adults | sort name")), ["Alice", "Carol"]); assert!(engine.execute(&pipeline("on users | out users")).is_err()); assert!(engine.plan(&pipeline("on users | out _permissions")).is_err()); let planned = engine.plan(&pipeline("on users as u | out u.copy")).unwrap(); assert!(planned.physical().is_write()); }
#[test] fn into_respects_the_memory_governor() { use og_core::MemoryGovernor; let limited = engine().with_memory_governor(MemoryGovernor::with_limit(64)); let error = limited.execute(&pipeline("on users | into archive")).unwrap_err().to_string(); assert!(error.contains("into"), "{error}"); assert!(materialize(&limited, "on archive").is_empty()); assert_eq!(materialize(&limited, "on users").len(), 3); let roomy = engine().with_memory_governor(MemoryGovernor::with_limit(64 * 1024 * 1024)); assert_eq!(roomy.execute(&pipeline("on users | into archive")).unwrap().output().statistics().inserted(), 3); }
