//! Additional query-engine invariants and regression tests.
#![cfg_attr(rustfmt, rustfmt_skip)]

use std::{ collections::BTreeSet, sync::{ atomic::{AtomicUsize, Ordering}, Arc, }, };
use og_core::{ engine::{Engine, EngineErrorKind}, query::{ CustomOperatorResult, ExecutionError, PlannerPipeline, PlannerStage, QueryRuntime, QueryRuntimeBuilder, ScanPlanLowerer, Span, StageName, }, storage::{CollectionId, DocumentId, MemoryStorage, StorageEngine}, Document, };

fn stage(name: &str, arguments: &str) -> PlannerStage { PlannerStage::new( StageName::parse(name).expect("valid stage name"), arguments, Span::new(0, arguments.len()), ) }
fn collection(name: &str) -> CollectionId { CollectionId::parse(name).expect("valid collection id") }
fn document_id(label: &str) -> DocumentId { if let Ok(id) = DocumentId::parse(label) { return id; } assert!(label.len() <= 9, "test document labels must fit in 9 bytes"); let mut ordinal = 0_u128; for index in 0..9 { ordinal *= 257; if let Some(byte) = label.as_bytes().get(index) { ordinal += u128::from(*byte) + 1; } } let rand_a = ((ordinal >> 62) & 0x0fff) as u16; let rand_b = (ordinal & ((1_u128 << 62) - 1)) as u64; let timestamp_ms = 1_700_000_000_000_u64; let value = ((timestamp_ms as u128) << 80) | (0x7_u128 << 76) | ((rand_a as u128) << 64) | (0b10_u128 << 62) | u128::from(rand_b); let hex = format!("{value:032x}"); let text = format!( "{}-{}-{}-{}-{}", &hex[0..8], &hex[8..12], &hex[12..16], &hex[16..20], &hex[20..32], ); DocumentId::parse(&text).expect("valid deterministic UUID v7 test document id") }
fn ids(count: usize) -> Vec<String> { (0..count) .map(|index| document_id(&format!("doc-{index:03}")).to_string()) .collect() }
fn as_u64(value: usize) -> u64 { u64::try_from(value).expect("test cardinality fits in u64") }
fn seed_ids(storage: &MemoryStorage, collection_name: &str, ids: impl IntoIterator<Item = String>) { let collection = collection(collection_name); let mut transaction = storage.begin().expect("begin seed transaction"); for id in ids { transaction .insert(&collection, document_id(&id), Arc::new(Document::default())) .expect("insert seed document"); } transaction.commit().expect("commit seed transaction"); }
fn default_runtime() -> Arc<QueryRuntime> { Arc::new( QueryRuntimeBuilder::new() .predicate(|_, _| Ok(true)) .set(|_, document| Ok(Arc::new(document.clone()))) .load(|_, document| Ok(Arc::new(document.clone()))) .custom(|_, _, _, _| Ok(CustomOperatorResult::Keep)) .build() .expect("valid default runtime"), ) }
fn engine(storage: Arc<MemoryStorage>, runtime: Arc<QueryRuntime>) -> Engine { Engine::new(storage, runtime, Arc::new(ScanPlanLowerer::new())) }

macro_rules! output_ids {
    ($result:expr) => {{
        $result
            .output()
            .rows()
            .iter()
            .map(|row| row.id().to_string().to_owned())
            .collect::<Vec<_>>()
    }};
}

fn stored_versions(
    storage: &MemoryStorage,
    collection_name: &str,
    expected_ids: &[String],
) -> Vec<u64> {
    let snapshot = storage.read().expect("read storage");
    let collection = collection(collection_name);

    expected_ids
        .iter()
        .map(|id| {
            snapshot
                .get(&collection, &document_id(id))
                .expect("read document")
                .expect("document exists")
                .version()
                .get()
        })
        .collect()
}

#[test] fn scans_are_sorted_for_multiple_input_sizes_and_insertion_orders() { for count in [0, 1, 2, 3, 8, 17, 32] { let expected = ids(count); let insertion_orders = [ expected.clone(), expected.iter().rev().cloned().collect(), { let mut interleaved = Vec::with_capacity(count); interleaved.extend(expected.iter().step_by(2).cloned()); interleaved.extend(expected.iter().skip(1).step_by(2).cloned()); interleaved }, ]; for insertion_order in insertion_orders { let storage = Arc::new(MemoryStorage::new()); seed_ids(&storage, "items", insertion_order); let engine = engine(Arc::clone(&storage), default_runtime()); let result = engine .execute(&PlannerPipeline::new("items", [])) .expect("scan succeeds"); assert_eq!(output_ids!(result), expected); assert_eq!(result.output().statistics().scanned(), as_u64(count)); assert_eq!(result.output().statistics().returned(), as_u64(count)); assert_eq!(result.output().statistics().filtered(), 0); assert_eq!(result.output().statistics().replaced(), 0); } } }
#[test] fn repeated_read_only_queries_are_stable_and_do_not_commit() { let storage = Arc::new(MemoryStorage::new()); let expected = ids(12); seed_ids(&storage, "items", expected.clone()); let initial_generation = storage.generation().expect("read initial generation"); let engine = engine(Arc::clone(&storage), default_runtime()); for _ in 0..10 { let result = engine .execute(&PlannerPipeline::new("items", [])) .expect("read query succeeds"); assert_eq!(output_ids!(result), expected); assert!(!result.output().committed()); assert_eq!( storage.generation().expect("read generation"), initial_generation, ); } }
#[test] fn successful_set_advances_each_document_once_per_execution() { let storage = Arc::new(MemoryStorage::new()); let expected = ids(9); seed_ids(&storage, "items", expected.clone()); let engine = engine(Arc::clone(&storage), default_runtime()); let query = PlannerPipeline::new("items", [stage("set", "visited = true")]); for execution_index in 1..=4 { let result = engine.execute(&query).expect("set succeeds"); assert!(result.output().committed()); assert_eq!( result.output().statistics().scanned(), as_u64(expected.len()) ); assert_eq!( result.output().statistics().returned(), as_u64(expected.len()) ); assert_eq!( result.output().statistics().replaced(), as_u64(expected.len()) ); let expected_version = 1 + execution_index as u64; assert_eq!( stored_versions(&storage, "items", &expected), vec![expected_version; expected.len()], ); } }
#[test] fn rejected_rows_are_never_passed_to_set() { let storage = Arc::new(MemoryStorage::new()); let expected = ids(10); seed_ids(&storage, "items", expected.clone()); let predicate_index = Arc::new(AtomicUsize::new(0)); let set_calls = Arc::new(AtomicUsize::new(0)); let predicate_counter = Arc::clone(&predicate_index); let set_counter = Arc::clone(&set_calls); let runtime = Arc::new( QueryRuntimeBuilder::new() .predicate(move |_, _| { let index = predicate_counter.fetch_add(1, Ordering::SeqCst); Ok(index % 3 != 1) }) .set(move |_, document| { set_counter.fetch_add(1, Ordering::SeqCst); Ok(Arc::new(document.clone())) }) .build() .expect("valid runtime"), ); let engine = engine(Arc::clone(&storage), runtime); let query = PlannerPipeline::new( "items", [stage("where", "selected"), stage("set", "visited = true")], ); let result = engine.execute(&query).expect("query succeeds"); let selected_indices = (0..expected.len()) .filter(|index| index % 3 != 1) .collect::<BTreeSet<_>>(); assert_eq!(set_calls.load(Ordering::SeqCst), selected_indices.len(),); assert_eq!( result.output().statistics().filtered(), as_u64(expected.len() - selected_indices.len()), ); assert_eq!( result.output().statistics().replaced(), as_u64(selected_indices.len()), ); let versions = stored_versions(&storage, "items", &expected); for (index, version) in versions.into_iter().enumerate() { let expected_version = if selected_indices.contains(&index) { 2 } else { 1 }; assert_eq!(version, expected_version); } }
#[test] fn failed_set_is_atomic_for_every_failure_position() { const DOCUMENT_COUNT: usize = 7; for failure_position in 0..DOCUMENT_COUNT { let storage = Arc::new(MemoryStorage::new()); let expected = ids(DOCUMENT_COUNT); seed_ids(&storage, "items", expected.clone()); let calls = Arc::new(AtomicUsize::new(0)); let counter = Arc::clone(&calls); let runtime = Arc::new( QueryRuntimeBuilder::new() .predicate(|_, _| Ok(true)) .set(move |_, document| { let index = counter.fetch_add(1, Ordering::SeqCst); if index == failure_position { return Err(ExecutionError::evaluation(format!( "failure at mutation index {index}", ))); } Ok(Arc::new(document.clone())) }) .build() .expect("valid failing runtime"), ); let engine = engine(Arc::clone(&storage), runtime); let query = PlannerPipeline::new("items", [stage("set", "visited = true")]); let error = engine.execute(&query).expect_err("query must fail"); assert!(matches!(error.kind(), EngineErrorKind::Execution(_),)); assert_eq!( stored_versions(&storage, "items", &expected), vec![1; DOCUMENT_COUNT], ); assert_eq!(storage.generation().expect("read generation"), 1,); } }
#[test] fn predicate_failure_never_mutates_storage() { const DOCUMENT_COUNT: usize = 6; for failure_position in 0..DOCUMENT_COUNT { let storage = Arc::new(MemoryStorage::new()); let expected = ids(DOCUMENT_COUNT); seed_ids(&storage, "items", expected.clone()); let predicate_calls = Arc::new(AtomicUsize::new(0)); let set_calls = Arc::new(AtomicUsize::new(0)); let predicate_counter = Arc::clone(&predicate_calls); let set_counter = Arc::clone(&set_calls); let runtime = Arc::new( QueryRuntimeBuilder::new() .predicate(move |_, _| { let index = predicate_counter.fetch_add(1, Ordering::SeqCst); if index == failure_position { return Err(ExecutionError::evaluation("synthetic predicate failure")); } Ok(true) }) .set(move |_, document| { set_counter.fetch_add(1, Ordering::SeqCst); Ok(Arc::new(document.clone())) }) .build() .expect("valid runtime"), ); let engine = engine(Arc::clone(&storage), runtime); let query = PlannerPipeline::new( "items", [stage("where", "selected"), stage("set", "visited = true")], ); engine.execute(&query).expect_err("query must fail"); assert_eq!(set_calls.load(Ordering::SeqCst), failure_position,); assert_eq!( stored_versions(&storage, "items", &expected), vec![1; DOCUMENT_COUNT], ); assert_eq!(storage.generation().expect("read generation"), 1,); } }
#[test] fn statistics_are_consistent_for_all_filter_cardinalities() { const DOCUMENT_COUNT: usize = 8; for kept_count in 0..=DOCUMENT_COUNT { let storage = Arc::new(MemoryStorage::new()); seed_ids(&storage, "items", ids(DOCUMENT_COUNT)); let calls = Arc::new(AtomicUsize::new(0)); let counter = Arc::clone(&calls); let runtime = Arc::new( QueryRuntimeBuilder::new() .predicate(move |_, _| { let index = counter.fetch_add(1, Ordering::SeqCst); Ok(index < kept_count) }) .set(|_, document| Ok(Arc::new(document.clone()))) .build() .expect("valid runtime"), ); let engine = engine(storage, runtime); let result = engine .execute(&PlannerPipeline::new("items", [stage("where", "selected")])) .expect("filter succeeds"); let statistics = result.output().statistics(); assert_eq!(statistics.scanned(), as_u64(DOCUMENT_COUNT)); assert_eq!(statistics.returned(), as_u64(kept_count)); assert_eq!(statistics.filtered(), as_u64(DOCUMENT_COUNT - kept_count),); assert_eq!( statistics.scanned(), statistics.returned() + statistics.filtered(), ); assert_eq!(statistics.replaced(), 0); assert!(!result.output().committed()); } }
#[test] fn empty_write_query_is_successful_without_advancing_generation() { let storage = Arc::new(MemoryStorage::new()); let initial_generation = storage.generation().expect("read initial generation"); let engine = engine(Arc::clone(&storage), default_runtime()); let query = PlannerPipeline::new("items", [stage("set", "visited = true")]); let result = engine.execute(&query).expect("empty write succeeds"); assert!(result.output().is_empty()); assert_eq!(result.output().statistics().scanned(), 0); assert_eq!(result.output().statistics().replaced(), 0); assert_eq!( storage.generation().expect("read final generation"), initial_generation, ); }
#[test] fn queries_never_cross_collection_boundaries() { let storage = Arc::new(MemoryStorage::new()); let users = ids(5); let orders = ids(3); seed_ids(&storage, "users", users.clone()); seed_ids(&storage, "orders", orders.clone()); let engine = engine(Arc::clone(&storage), default_runtime()); let users_result = engine .execute(&PlannerPipeline::new("users", [])) .expect("users scan succeeds"); let orders_result = engine .execute(&PlannerPipeline::new("orders", [])) .expect("orders scan succeeds"); assert_eq!(output_ids!(users_result), users); assert_eq!(output_ids!(orders_result), orders); let mutation = PlannerPipeline::new("users", [stage("set", "visited = true")]); engine.execute(&mutation).expect("users mutation succeeds"); assert_eq!(stored_versions(&storage, "users", &ids(5)), vec![2; 5],); assert_eq!(stored_versions(&storage, "orders", &ids(3)), vec![1; 3],); }
#[test] fn runtime_callbacks_are_invoked_exactly_once_per_relevant_row() { let storage = Arc::new(MemoryStorage::new()); seed_ids(&storage, "items", ids(25)); let predicate_calls = Arc::new(AtomicUsize::new(0)); let set_calls = Arc::new(AtomicUsize::new(0)); let predicate_counter = Arc::clone(&predicate_calls); let set_counter = Arc::clone(&set_calls); let runtime = Arc::new( QueryRuntimeBuilder::new() .predicate(move |_, _| { predicate_counter.fetch_add(1, Ordering::SeqCst); Ok(true) }) .set(move |_, document| { set_counter.fetch_add(1, Ordering::SeqCst); Ok(Arc::new(document.clone())) }) .build() .expect("valid runtime"), ); let engine = engine(storage, runtime); let query = PlannerPipeline::new( "items", [stage("where", "selected"), stage("set", "visited = true")], ); let result = engine.execute(&query).expect("query succeeds"); assert_eq!(predicate_calls.load(Ordering::SeqCst), 25); assert_eq!(set_calls.load(Ordering::SeqCst), 25); assert_eq!(result.output().statistics().scanned(), 25); assert_eq!(result.output().statistics().returned(), 25); assert_eq!(result.output().statistics().replaced(), 25); }
#[test] fn planning_failure_is_repeatable_and_side_effect_free() { let storage = Arc::new(MemoryStorage::new()); seed_ids(&storage, "items", ids(4)); let engine = engine(Arc::clone(&storage), default_runtime()); let invalid_query = PlannerPipeline::new("items", [stage("where", "")]); for _ in 0..5 { let error = engine .execute(&invalid_query) .expect_err("planning must fail"); assert!(matches!(error.kind(), EngineErrorKind::Planning(_),)); assert_eq!(storage.generation().expect("read generation"), 1,); assert_eq!(stored_versions(&storage, "items", &ids(4)), vec![1; 4],); } }
