//! End-to-end query-engine integration tests.
#![cfg_attr(rustfmt, rustfmt_skip)]

use std::sync::{ atomic::{AtomicUsize, Ordering}, Arc, };
use og_core::{ engine::{Engine, EngineErrorKind}, query::{ CustomOperatorResult, ExecutionError, ExecutionErrorKind, PlannerPipeline, PlannerStage, QueryRuntimeBuilder, ScanPlanLowerer, Span, StageName, }, storage::{ CollectionId, DocumentId, MemoryStorage, ScanOptions, StorageEngine, VersionPrecondition, }, Document, };

fn stage(name: &str, arguments: &str) -> PlannerStage { PlannerStage::new( StageName::parse(name).expect("valid test stage name"), arguments, Span::new(0, arguments.len()), ) }
fn collection(name: &str) -> CollectionId { CollectionId::parse(name).expect("valid test collection") }
fn document_id(label: &str) -> DocumentId { if let Ok(id) = DocumentId::parse(label) { return id; } assert!(label.len() <= 9, "test document labels must fit in 9 bytes"); let mut ordinal = 0_u128; for index in 0..9 { ordinal *= 257; if let Some(byte) = label.as_bytes().get(index) { ordinal += u128::from(*byte) + 1; } } let rand_a = ((ordinal >> 62) & 0x0fff) as u16; let rand_b = (ordinal & ((1_u128 << 62) - 1)) as u64; let timestamp_ms = 1_700_000_000_000_u64; let value = ((timestamp_ms as u128) << 80) | (0x7_u128 << 76) | ((rand_a as u128) << 64) | (0b10_u128 << 62) | u128::from(rand_b); let hex = format!("{value:032x}"); let text = format!( "{}-{}-{}-{}-{}", &hex[0..8], &hex[8..12], &hex[12..16], &hex[16..20], &hex[20..32], ); DocumentId::parse(&text).expect("valid deterministic UUID v7 test document id") }
fn seed(storage: &MemoryStorage, collection_name: &str, documents: &[(&str, Document)]) { let collection = collection(collection_name); let mut transaction = storage.begin().expect("begin seed transaction"); for (id, document) in documents { transaction .insert(&collection, document_id(id), Arc::new(document.clone())) .expect("insert seed document"); } transaction.commit().expect("commit seed transaction"); }
fn runtime() -> Arc<og_core::query::QueryRuntime> { Arc::new( QueryRuntimeBuilder::new() .predicate(|_, _| Ok(true)) .set(|_, document| Ok(Arc::new(document.clone()))) .load(|_, document| Ok(Arc::new(document.clone()))) .custom(|_, _, _, _| Ok(CustomOperatorResult::Keep)) .build() .expect("valid test runtime"), ) }
fn engine(storage: Arc<MemoryStorage>, runtime: Arc<og_core::query::QueryRuntime>) -> Engine { Engine::new(storage, runtime, Arc::new(ScanPlanLowerer::new())) }

#[test] fn empty_collection_returns_an_empty_successful_result() { let storage = Arc::new(MemoryStorage::new()); let engine = engine(storage, runtime()); let query = PlannerPipeline::new("users", []); let result = engine.execute(&query).expect("query succeeds"); let output = result.output(); assert!(output.is_empty()); assert_eq!(output.statistics().scanned(), 0); assert_eq!(output.statistics().returned(), 0); assert!(!output.committed()); }
#[test] fn unsupported_load_is_reported_as_an_execution_error() { let storage = Arc::new(MemoryStorage::new()); seed(&storage, "users", &[("alice", Document::default())]); let runtime = Arc::new( QueryRuntimeBuilder::new() .predicate(|_, _| Ok(true)) .set(|_, document| Ok(Arc::new(document.clone()))) .build() .expect("valid runtime without load support"), ); let engine = engine(storage, runtime); let query = PlannerPipeline::new("users", [stage("load", "profile")]); let error = engine.execute(&query).expect_err("load must fail"); let EngineErrorKind::Execution(execution) = error.kind() else { panic!("expected execution error, got {error}"); }; assert!(matches!( execution.kind(), ExecutionErrorKind::UnsupportedOperator { .. }, )); }
#[test] fn operator_order_is_preserved_across_planning_and_execution() { let storage = Arc::new(MemoryStorage::new()); seed(&storage, "users", &[("alice", Document::default())]); let sequence = Arc::new(AtomicUsize::new(0)); let predicate_sequence = Arc::clone(&sequence); let set_sequence = Arc::clone(&sequence); let runtime = Arc::new( QueryRuntimeBuilder::new() .predicate(move |_, _| { assert_eq!(predicate_sequence.fetch_add(1, Ordering::SeqCst), 0,); Ok(true) }) .set(move |_, document| { assert_eq!(set_sequence.fetch_add(1, Ordering::SeqCst), 1,); Ok(Arc::new(document.clone())) }) .build() .expect("valid ordered runtime"), ); let engine = engine(storage, runtime); let query = PlannerPipeline::new( "users", [ stage("where", "enabled == true"), stage("set", "visited = true"), ], ); let result = engine.execute(&query).expect("query succeeds"); assert_eq!(sequence.load(Ordering::SeqCst), 2); assert_eq!(result.output().len(), 1); assert!(result.output().committed()); let physical = result.planned().physical(); let names = physical .operators() .iter() .map(|operator| operator.name()) .collect::<Vec<_>>(); assert_eq!(names, ["filter", "set"]); }
#[test] fn invalid_stage_arguments_fail_before_storage_execution() { let storage = Arc::new(MemoryStorage::new()); seed(&storage, "users", &[("alice", Document::default())]); let engine = engine(Arc::clone(&storage), runtime()); let query = PlannerPipeline::new("users", [stage("where", "")]); let error = engine.execute(&query).expect_err("planning must fail"); assert!(matches!(error.kind(), EngineErrorKind::Planning(_),)); assert_eq!(storage.generation().expect("read generation"), 1); assert_eq!(storage.document_count().expect("count documents"), 1); }
#[test] fn storage_remains_usable_after_a_failed_write_query() { let storage = Arc::new(MemoryStorage::new()); seed(&storage, "users", &[("alice", Document::default())]); let failing_runtime = Arc::new( QueryRuntimeBuilder::new() .predicate(|_, _| Ok(true)) .set(|_, _| Err(ExecutionError::evaluation("synthetic failure"))) .build() .expect("valid failing runtime"), ); let failing_engine = engine(Arc::clone(&storage), failing_runtime); let write = PlannerPipeline::new("users", [stage("set", "visited = true")]); failing_engine.execute(&write).expect_err("write must fail"); let healthy_engine = engine(Arc::clone(&storage), runtime()); let read = PlannerPipeline::new("users", []); let result = healthy_engine .execute(&read) .expect("subsequent read succeeds"); assert_eq!(result.output().len(), 1); assert_eq!(result.output().rows()[0].id(), &document_id("alice"),); }
#[test] fn explicit_storage_precondition_remains_enforced_after_queries() { let storage = Arc::new(MemoryStorage::new()); seed(&storage, "users", &[("alice", Document::default())]); let engine = engine(Arc::clone(&storage), runtime()); let read = PlannerPipeline::new("users", []); engine.execute(&read).expect("read query succeeds"); let mut transaction = storage.begin().expect("begin transaction"); let error = transaction .replace( &collection("users"), &document_id("alice"), Arc::new(Document::default()), VersionPrecondition::Exact( og_core::storage::DocumentVersion::INITIAL .next() .expect("valid version"), ), ) .expect_err("stale precondition must fail"); assert!(error.to_string().contains("version")); }
#[test] fn scan_options_remain_independent_from_query_execution() { let storage = Arc::new(MemoryStorage::new()); seed( &storage, "users", &[ ("alice", Document::default()), ("bob", Document::default()), ("charlie", Document::default()), ], ); let engine = engine(Arc::clone(&storage), runtime()); engine .execute(&PlannerPipeline::new("users", [])) .expect("query succeeds"); let snapshot = storage.read().expect("read storage"); let rows = snapshot .scan(&collection("users"), ScanOptions::default().with_limit(2)) .expect("limited scan succeeds"); assert_eq!(rows.len(), 2); assert_eq!(rows[0].id(), &document_id("alice")); assert_eq!(rows[1].id(), &document_id("bob")); }
