#![cfg_attr(rustfmt, rustfmt_skip)]
use og_core::query::{ lex, parse, parse_tokens, LexErrorKind, ParseErrorKind, QueryParseError, SourceKeyword, Spanned, TokenKind, };

#[test] fn parses_source_only_query() { let source = "from users"; let pipeline = parse(source).expect("query must parse"); assert_eq!(pipeline.source().keyword(), SourceKeyword::From,); assert_eq!(pipeline.source().collection_name(source), Some("users"),); assert!(pipeline.is_source_only()); assert_eq!(pipeline.stage_count(), 0); assert_eq!(pipeline.text(source), Some(source)); }
#[test] fn parses_on_source_alias_without_normalizing_it() { let source = "on users"; let pipeline = parse(source).expect("query must parse"); assert_eq!(pipeline.source().keyword(), SourceKeyword::On,); assert_eq!(pipeline.source().collection_name(source), Some("users"),); }
#[test] fn preserves_source_alias_for_future_normalization() { let from_source = "from users"; let on_source = "on users"; let from_pipeline = parse(from_source).expect("from query must parse"); let on_pipeline = parse(on_source).expect("on query must parse"); assert_ne!( from_pipeline.source().keyword(), on_pipeline.source().keyword(), ); assert_eq!( from_pipeline.source().collection_name(from_source), on_pipeline.source().collection_name(on_source), ); }
#[test] fn parses_system_collection() { let source = "from _og.operations"; let pipeline = parse(source).expect("query must parse"); assert_eq!( pipeline.source().collection_name(source), Some("_og.operations"), ); }
#[test] fn parses_nested_collection_name() { let source = "from tenant.analytics.events"; let pipeline = parse(source).expect("query must parse"); assert_eq!( pipeline.source().collection_name(source), Some("tenant.analytics.events"), ); }
#[test] fn parses_filter_pipeline() { let source = r#"from users | where country == "FR""#; let pipeline = parse(source).expect("query must parse"); assert_eq!(pipeline.stage_count(), 1); let stage = pipeline.stage(0).expect("where stage must exist"); assert_eq!(stage.name_text(source), Some("where")); assert_eq!(stage.arguments_text(source), Some(r#"country == "FR""#),); assert!(stage.has_arguments()); }
#[test] fn parses_mutation_pipeline() { let source = "from users | where active == true | set enabled = true"; let pipeline = parse(source).expect("query must parse"); assert_eq!(pipeline.stage_count(), 2); let where_stage = pipeline.stage(0).expect("where stage must exist"); let set_stage = pipeline.stage(1).expect("set stage must exist"); assert_eq!(where_stage.name_text(source), Some("where"),); assert_eq!(where_stage.arguments_text(source), Some("active == true"),); assert_eq!(set_stage.name_text(source), Some("set"),); assert_eq!(set_stage.arguments_text(source), Some("enabled = true"),); }
#[test] fn parses_custom_stage() { let source = "from users | inspect verbose"; let pipeline = parse(source).expect("query must parse"); let stage = pipeline.stage(0).expect("custom stage must exist"); assert_eq!(stage.name_text(source), Some("inspect")); assert_eq!(stage.arguments_text(source), Some("verbose"),); }
#[test] fn parses_stage_without_arguments() { let source = "from users | inspect"; let pipeline = parse(source).expect("query must parse"); let stage = pipeline.stage(0).expect("custom stage must exist"); assert_eq!(stage.name_text(source), Some("inspect")); assert_eq!(stage.arguments_text(source), Some("")); assert!(!stage.has_arguments()); }
#[test] fn preserves_pipeline_stage_order() { let source = "from users | first alpha | second beta | third gamma"; let pipeline = parse(source).expect("query must parse"); let stage_names = pipeline .iter_stages() .map(|stage| stage.name_text(source).expect("stage name must resolve")) .collect::<Vec<_>>(); assert_eq!(stage_names, vec!["first", "second", "third"],); }
#[test] fn preserves_exact_stage_arguments() { let source = r#"from users | where profile.country == "FR""#; let pipeline = parse(source).expect("query must parse"); let stage = pipeline.stage(0).expect("where stage must exist"); assert_eq!( stage.arguments_text(source), Some(r#"profile.country == "FR""#), ); }
#[test] fn handles_parenthesized_arguments() { let source = r#"from users | where active and (country == "FR")"#; let pipeline = parse(source).expect("query must parse"); let stage = pipeline.stage(0).expect("where stage must exist"); assert_eq!( stage.arguments_text(source), Some(r#"active and (country == "FR")"#), ); }
#[test] fn handles_nested_parentheses() { let source = "from users | where (active and (age >= 18))"; let pipeline = parse(source).expect("query must parse"); let stage = pipeline.stage(0).expect("where stage must exist"); assert_eq!( stage.arguments_text(source), Some("(active and (age >= 18))"), ); }
#[test] fn pipe_inside_parentheses_does_not_split_pipeline() { let source = "from users | custom (left | right) | inspect"; let pipeline = parse(source).expect("query must parse"); assert_eq!(pipeline.stage_count(), 2); assert_eq!( pipeline .stage(0) .expect("custom stage must exist") .arguments_text(source), Some("(left | right)"), ); assert_eq!( pipeline .stage(1) .expect("inspect stage must exist") .name_text(source), Some("inspect"), ); }
#[test] fn pipe_inside_string_does_not_split_pipeline() { let source = r#"from users | where value == "left | right" | inspect"#; let pipeline = parse(source).expect("query must parse"); assert_eq!(pipeline.stage_count(), 2); assert_eq!( pipeline .stage(0) .expect("where stage must exist") .arguments_text(source), Some(r#"value == "left | right""#), ); }
#[test] fn lexer_and_parser_can_be_called_separately() { let source = r#"from users | where country == "FR""#; let stream = lex(source).expect("lexing must succeed"); assert_eq!( stream.kinds().collect::<Vec<_>>(), vec![ TokenKind::From, TokenKind::Identifier, TokenKind::Pipe, TokenKind::Where, TokenKind::Identifier, TokenKind::EqualEqual, TokenKind::String, TokenKind::End, ], ); let pipeline = parse_tokens(&stream).expect("parsing must succeed"); assert_eq!(pipeline.source().collection_name(source), Some("users"),); }
#[test] fn token_stream_preserves_exact_lexemes() { let source = r#"from users | where country == "FR""#; let stream = lex(source).expect("lexing must succeed"); let lexemes = stream .significant_tokens() .map(|token| stream.lexeme(token).expect("token span must resolve")) .collect::<Vec<_>>(); assert_eq!( lexemes, vec!["from", "users", "|", "where", "country", "==", r#""FR""#,], ); }
#[test] fn whitespace_does_not_change_token_kinds() { let compact = lex("from users|where age>=18").expect("compact query must lex"); let formatted = lex("from users\n| where age >= 18").expect("formatted query must lex"); assert_eq!( compact.kinds().collect::<Vec<_>>(), formatted.kinds().collect::<Vec<_>>(), ); }
#[test] fn whitespace_remains_visible_through_spans() { let compact_source = "from users|where age>=18"; let formatted_source = "from users | where age >= 18"; let compact = parse(compact_source).expect("query must parse"); let formatted = parse(formatted_source).expect("query must parse"); assert_ne!(compact.span(), formatted.span()); assert_eq!( compact.source().collection_name(compact_source), formatted.source().collection_name(formatted_source), ); assert_eq!( compact .stage(0) .expect("stage must exist") .name_text(compact_source), formatted .stage(0) .expect("stage must exist") .name_text(formatted_source), ); }
#[test] fn identical_queries_produce_identical_ast() { let source = "from users | where age >= 18"; let first = parse(source).expect("query must parse"); let second = parse(source).expect("query must parse"); assert_eq!(first, second); }
#[test] fn different_literals_remain_syntactically_distinguishable() { let first_source = "from users | where age >= 18"; let second_source = "from users | where age >= 42"; let first = parse(first_source).expect("query must parse"); let second = parse(second_source).expect("query must parse"); let first_stage = first.stage(0).expect("first where stage must exist"); let second_stage = second.stage(0).expect("second where stage must exist"); assert_eq!( first_stage.name_text(first_source), second_stage.name_text(second_source), ); assert_ne!( first_stage.arguments_text(first_source), second_stage.arguments_text(second_source), ); }
#[test] fn different_literals_have_the_same_lexical_shape() { let first = lex("from users | where age >= 18").expect("first query must lex"); let second = lex("from users | where age >= 42").expect("second query must lex"); assert_eq!( first.kinds().collect::<Vec<_>>(), second.kinds().collect::<Vec<_>>(), ); }
#[test] fn different_collections_remain_distinguishable() { let users_source = "from users | where id == 18"; let orders_source = "from orders | where id == 18"; let users = parse(users_source).expect("users query must parse"); let orders = parse(orders_source).expect("orders query must parse"); assert_ne!( users.source().collection_name(users_source), orders.source().collection_name(orders_source), ); }
#[test] fn different_fields_remain_distinguishable() { let age_source = "from users | where age >= 18"; let score_source = "from users | where score >= 18"; let age = parse(age_source).expect("age query must parse"); let score = parse(score_source).expect("score query must parse"); assert_ne!( age.stage(0) .expect("age stage must exist") .arguments_text(age_source), score .stage(0) .expect("score stage must exist") .arguments_text(score_source), ); }
#[test] fn optimization_inputs_can_distinguish_text_shape_and_semantics() { let first_source = "from users | where age >= 18"; let second_source = "from users | where age >= 42"; let third_source = "from orders | where total >= 42"; let first_tokens = lex(first_source).expect("first query must lex"); let second_tokens = lex(second_source).expect("second query must lex"); let third_tokens = lex(third_source).expect("third query must lex"); assert_eq!( first_tokens.kinds().collect::<Vec<_>>(), second_tokens.kinds().collect::<Vec<_>>(), ); assert_eq!( second_tokens.kinds().collect::<Vec<_>>(), third_tokens.kinds().collect::<Vec<_>>(), ); let first = parse(first_source).expect("first query must parse"); let second = parse(second_source).expect("second query must parse"); let third = parse(third_source).expect("third query must parse"); assert_eq!( first.source().collection_name(first_source), second.source().collection_name(second_source), ); assert_ne!( first .stage(0) .expect("first stage must exist") .arguments_text(first_source), second .stage(0) .expect("second stage must exist") .arguments_text(second_source), ); assert_ne!( second.source().collection_name(second_source), third.source().collection_name(third_source), ); }
#[test] fn rejects_empty_query() { let error = parse("").expect_err("empty query must fail"); let QueryParseError::Parse(error) = error else { panic!("expected parser error"); }; assert_eq!( error.kind(), &ParseErrorKind::ExpectedSourceKeyword { found: TokenKind::End, }, ); }
#[test] fn rejects_query_without_source_keyword() { let error = parse("users").expect_err("query must fail"); let QueryParseError::Parse(error) = error else { panic!("expected parser error"); }; assert_eq!( error.kind(), &ParseErrorKind::ExpectedSourceKeyword { found: TokenKind::Identifier, }, ); }
#[test] fn rejects_missing_collection_name() { let error = parse("from").expect_err("query must fail"); let QueryParseError::Parse(error) = error else { panic!("expected parser error"); }; assert_eq!( error.kind(), &ParseErrorKind::ExpectedCollectionName { found: TokenKind::End, }, ); }
#[test] fn rejects_invalid_qualified_collection() { let error = parse("from _og.").expect_err("query must fail"); let QueryParseError::Parse(error) = error else { panic!("expected parser error"); }; assert_eq!( error.kind(), &ParseErrorKind::ExpectedNameAfterDot { found: TokenKind::End, }, ); }
#[test] fn rejects_stage_without_pipe() { let error = parse("from users where age > 18").expect_err("query must fail"); let QueryParseError::Parse(error) = error else { panic!("expected parser error"); }; assert_eq!( error.kind(), &ParseErrorKind::ExpectedPipe { found: TokenKind::Where, }, ); }
#[test] fn rejects_trailing_pipe() { let error = parse("from users |").expect_err("query must fail"); let QueryParseError::Parse(error) = error else { panic!("expected parser error"); }; assert_eq!( error.kind(), &ParseErrorKind::ExpectedStageName { found: TokenKind::End, }, ); }
#[test] fn rejects_unclosed_parenthesis() { let error = parse("from users | where (age >= 18").expect_err("query must fail"); let QueryParseError::Parse(error) = error else { panic!("expected parser error"); }; assert!(matches!( error.kind(), ParseErrorKind::UnclosedParenthesis { .. }, )); }
#[test] fn rejects_unexpected_right_parenthesis() { let error = parse("from users | where age >= 18)").expect_err("query must fail"); let QueryParseError::Parse(error) = error else { panic!("expected parser error"); }; assert_eq!(error.kind(), &ParseErrorKind::UnexpectedRightParenthesis,); }
#[test] fn distinguishes_lexer_errors_from_parser_errors() { let lexical = parse("from users @").expect_err("query must fail lexically"); assert!(matches!(lexical, QueryParseError::Lex(_),)); let syntax = parse("users").expect_err("query must fail syntactically"); assert!(matches!(syntax, QueryParseError::Parse(_),)); }
#[test] fn exposes_lexical_error_kind() { let error = lex("from users @").expect_err("lexing must fail"); assert_eq!( error.kind(), &LexErrorKind::UnexpectedCharacter { character: '@' }, ); }
#[test] fn query_ast_types_are_thread_safe() { fn assert_send_and_sync<T: Send + Sync>() {} assert_send_and_sync::<og_core::query::PipelineAst>(); assert_send_and_sync::<og_core::query::SourceAst>(); assert_send_and_sync::<og_core::query::StageAst>(); assert_send_and_sync::<og_core::query::QueryParseError>(); }
