//! Tests d'intégration de la couche sémantique.
#![cfg_attr(rustfmt, rustfmt_skip)]

use og_core::model::{ compare, equals, Capabilities, Capability, CoercionPolicy, Document, FieldPath, ResolvedValue, Value, ValueCapabilities, };

#[test] fn resolve_simple_field() { let document = Document::from_fields([("name", Value::from("Thomas"))]); let path = FieldPath::parse("name").unwrap(); assert_eq!( path.resolve(&document), ResolvedValue::Present(&Value::from("Thomas")), ); }
#[test] fn resolve_nested_field() { let address = Document::from_fields([("city", Value::from("Paris"))]); let document = Document::from_fields([("address", Value::from(address))]); let path = FieldPath::parse("address.city").unwrap(); assert_eq!( path.resolve(&document), ResolvedValue::Present(&Value::from("Paris")), ); }
#[test] fn missing_is_not_null() { let document = Document::from_fields([("name", Value::Null)]); let null_path = FieldPath::parse("name").unwrap(); let missing_path = FieldPath::parse("age").unwrap(); assert!(null_path.resolve(&document).is_null()); assert!(missing_path.resolve(&document).is_missing()); }
#[test] fn capabilities_follow_the_physical_representation() { let value = Value::from(18_i64); let capabilities = value.capabilities(); assert!(capabilities.contains(Capability::Comparable)); assert!(capabilities.contains(Capability::Summable)); assert!(capabilities.contains(Capability::Searchable)); assert!(!capabilities.contains(Capability::Temporal)); }
#[test] fn nested_object_is_searchable() { let document = Document::from_fields([("name", Value::from("Thomas"))]); let value = Value::from(document); assert_eq!(value.capabilities(), Capabilities::SEARCHABLE); }
#[test] fn implicit_coercion_allows_number_string_equality() { assert_eq!( equals( &Value::from(18_i64), &Value::from("18"), CoercionPolicy::Implicit, ), Ok(true), ); }
#[test] fn strict_policy_preserves_the_physical_representation() { assert!(equals( &Value::from(18_i64), &Value::from("18"), CoercionPolicy::Strict, ) .is_err()); }
#[test] fn lexical_string_order_is_preserved() { assert_eq!( compare( &Value::from("18"), &Value::from("2"), CoercionPolicy::Implicit, ) .unwrap() .is_equal(), false, ); }
#[test] fn comparison_uses_the_field_resolution_result() { let document = Document::from_fields([("age", Value::from("18"))]); let path = FieldPath::parse("age").unwrap(); let value = match path.resolve(&document) { ResolvedValue::Present(value) => value, _ => panic!("expected value"), }; assert_eq!( equals(value, &Value::from(18_i64), CoercionPolicy::Implicit,), Ok(true), ); }
#[test] fn missing_field_is_never_compared() { let document = Document::new(); let path = FieldPath::parse("age").unwrap(); assert!(matches!(path.resolve(&document), ResolvedValue::Missing)); }
#[test] fn object_navigation_and_comparison_work_together() { let profile = Document::from_fields([("age", Value::from("42"))]); let document = Document::from_fields([("profile", Value::from(profile))]); let path = FieldPath::parse("profile.age").unwrap(); let value = match path.resolve(&document) { ResolvedValue::Present(value) => value, _ => panic!("expected value"), }; assert_eq!( equals(value, &Value::from(42_i64), CoercionPolicy::Implicit,), Ok(true), ); }
#[test] fn complete_semantic_pipeline() { let profile = Document::from_fields([("age", Value::from("18"))]); let document = Document::from_fields([("profile", Value::from(profile))]); let path = FieldPath::parse("profile.age").unwrap(); let value = match path.resolve(&document) { ResolvedValue::Present(value) => value, _ => panic!("expected value"), }; assert_eq!(value.capabilities().contains(Capability::Searchable), true); assert_eq!( equals(value, &Value::from(18_i64), CoercionPolicy::Implicit,), Ok(true), ); }
