[package]
name = "og-llama-common-chat"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[features]
default = []
cuda = ["llama-cpp-sys-2/cuda"]
cuda-no-vmm = ["cuda", "llama-cpp-sys-2/cuda-no-vmm"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
llama-cpp-sys-2 = { version = "=0.1.156", features = ["common"] }

[build-dependencies]
cc = "1"
